[versions]
compile-sdk = "34"
min-sdk = "26"
target-sdk = "34"
junit = "4.13.2"
junit-version = "1.1.5"
espresso-core = "3.5.1"
material = "1.10.0"


[libraries]
##########################################  系统库  ############################################################################
android-view-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.1.4" }
android-view-flexbox = { group = "com.google.android.flexbox", name = "flexbox", version = "3.0.0" }
android-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.12.0" }
android-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.4.1" }
android-webkit = {group = "androidx.webkit", name = "webkit", version = "1.4.0"}

##########################################  开发基础库  ############################################################################
cloud-api = { group = "io.github.cangHW", name = "Cloud-Api", version = "1.1.4.1" }
cloud-compiler = { group = "io.github.cangHW", name = "Cloud-Compiler", version = "1.1.4.1" }
cloud-plugin = { group = "io.github.cangHW", name = "Cloud-Plugin", version = "1.1.3.4" }

core-framework = {group = "io.github.cangHW", name="Service-CoreFramework", version="0.4.17"}
service-apihttp = {group = "io.github.cangHW", name="Service-Apihttp", version="0.0.9"}
service-threadpool = {group = "io.github.cangHW", name="Service-Threadpool", version="0.0.8"}
service-imageloader = {group = "io.github.cangHW", name="Service-Imageloader", version="0.0.7"}
service-webview = {group = "io.github.cangHW", name="Service-Webview", version="0.0.11"}
service-webview-bridge = {group = "io.github.cangHW", name="Service-WebBridge-Ds", version="0.0.8"}

##########################################  三方库  ############################################################################
# 网络库
http-ok = { group = "com.squareup.okhttp3", name = "okhttp", version = "4.11.0" }
http-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version = "2.9.0" }

# 图片库
image-glide = { group = "com.github.bumptech.glide", name = "glide", version = "4.16.0" }
image-lottie = { group = "com.airbnb.android", name = "lottie", version = "6.0.0" }

# 线程库
thread-rxjava = {group = "io.reactivex.rxjava2", name = "rxjava", version = "2.2.9"}
thread-rxandroid = {group = "io.reactivex.rxjava2", name = "rxandroid", version = "2.1.1"}

# 动态化
bytecode-buddy = {group = "net.bytebuddy", name = "byte-buddy", version = "1.15.4"}
bytecode-buddyandroid = {group = "net.bytebuddy", name = "byte-buddy-android", version = "1.15.4"}

# 数据库
room-api = { group = "androidx.room", name = "room-runtime", version = "2.5.2" }
room-compiler = { group = "androidx.room", name = "room-compiler", version = "2.5.2" }

# 压缩库
file-zip = { group = "net.lingala.zip4j", name = "zip4j", version = "2.11.5" }

# json 解析库
json-gson = { group = "com.google.code.gson", name = "gson", version = "2.10.1" }

# 类似 SharedPreferences, 高性能键值对存储库
sp-mmkv = { group = "com.tencent", name = "mmkv", version = "1.2.11" }


[plugins]
android-application = { id = "com.android.application", version = "8.5.0" }
android-library = { id = "com.android.library", version = "8.5.0" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version = "1.7.10" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "1.7.10" }

[bundles]
# 动态化
bytecode = ['bytecode-buddy', 'bytecode-buddyandroid']
# 线程
thread = ['thread-rxjava', 'thread-rxandroid']
# 网络
http = ['http-ok', 'http-retrofit']
# 图片
image = ['image-glide', 'image-lottie']

